CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(70) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Gender CHAR(1) NULL,
    RG VARCHAR(15) NULL,
    CPF CHAR(14) NULL,
    MotherName VARCHAR(70) NULL,
    RegistrationStatus CHAR(1) NOT NULL,
    RegistrationDate DATETIME NOT NULL
);

CREATE TABLE Contacts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Phone VARCHAR(15) NULL,
    Mobile VARCHAR(15) NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE DeliveryAddresses (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    AddressName VARCHAR(100) NOT NULL,
    ZIPCode CHAR(10) NOT NULL,
    State CHAR(2) NOT NULL,
    City VARCHAR(120) NOT NULL,
    District VARCHAR(200) NOT NULL,
    Address VARCHAR(200) NOT NULL,
    Number VARCHAR(20) NULL,
    Complement VARCHAR(30) NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Departments (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE UserDepartments (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    DepartmentId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (DepartmentId) REFERENCES Departments(Id) ON DELETE CASCADE
);


